### PR TITLE
cgo: declare rules for each supported mode, select in aspect

### LINKED ISSUE #1592: cgo does not propagate mode. sys/unix is broken with race = "on"
I'm trying version 0.13.0 of rules_go and gazelle. Thanks for the `# gazelle:proto disable_global`, it is great, now I don't need to wait for the protoc to be compiled.

But I'm getting the following errors:
```console
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/libgo_default_library.cgo_c_lib.lo the table of contents is empty (no object file members in the library define global symbols)
ERROR: /Users/ash2k/go/src/github.com/atlassian/smith/vendor/golang.org/x/sys/unix/BUILD.bazel:3:1: GoCompile vendor/golang.org/x/sys/unix/darwin_amd64_race_stripped/go_default_library~/github.com/atlassian/smith/vendor/golang.org/x/sys/unix.a~partial.a failed (Exit 1)
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:148:5: undefined: raceenabled
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:150:4: undefined: raceWriteRange
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:153:4: undefined: raceAcquire
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:160:5: undefined: raceenabled
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:161:3: undefined: raceReleaseMerge
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:164:5: undefined: raceenabled
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:165:3: undefined: raceReadRange
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:363:5: undefined: raceenabled
/private/var/tmp/_bazel_ash2k/18feaf204f522c9679e75c03985bfc8f/sandbox/darwin-sandbox/582/execroot/com_github_atlassian_smith/bazel-out/darwin-fastbuild/bin/vendor/golang.org/x/sys/unix/darwin_amd64_stripped/go_default_library.cgo_codegen~/syscall_unix.cgo1.go:364:3: undefined: raceReleaseMerge
GoCompile: error running subcommand: exit status 2
```
I've tried nuking everything with `rm -rf /private/var/tmp/_bazel_<user>` (I thought maybe this is the recent OS update...) but I'm getting the same error regardless. This is on latest macOS, bazel 0.15.0. Same code and same dependencies work fine with `0.12.1`.

To reproduce:
- clone `https://github.com/atlassian/smith` into your gopath
- checkout `rules_0.13.0` branch
- run `dep ensure` (you need to have `dep` installed)
- run `make test`

### PR DESCRIPTION
**Pull request by jayconrod**
go_binary and go_test allow developers to set mode attributes that
affect build tags, such as goos, goarch, race, and msan. These
attributes are propagated with an aspected over "deps" and "embed"
edges. Each rule the aspect visits must return a GoLibrary provider.

Unfortunately, our cgo implementation declares cc_library,
objc_library, and cc_binary rules that depend on sources generated by
_cgo_codegen. _cgo_codegen performs source filtering using build
tags. The native rules can't depend on a platform-specific GoSource
provider created by the aspect.

This change introduces separate _cgo_codegen and cc_library rules for
each platform. A new rule, _cgo_select_embed produces GoLibrary and
GoSource providers. The resolve function called by the aspect can
produce a GoSource for alternate platforms.

This change increases load and analysis time by about 15% (measured by
building tests/integration/popular_repos, cold starting Bazel but with
a warm disk cache). However, this is necessary to build
golang.org/x/sys/unix in alternate modes.

Fixes #1592

### CODE REVIEW

**Comment by jayconrod** [comment]
@ianthehat PTAL. I think this is the only way to do this without being able to perform C/C++/ObjC compile / link actions inside `go_library`. However, there's a significant performance penalty in loading and analysis, since there are a lot of extra rules.

**Comment by steeve** [comment]
Note that bazel master is now exposing the `cc` provider to Skylark \o/ ! Not sure it's in 0.16 though

**Comment by jayconrod** [comment]
@steeve We get `cc` providers already from `cc_library` dependencies? Did you mean something else?

I'm not sure if they've exposed a way to create C/C++ compile / link actions. That would be really useful because we wouldn't need to use `cc_library` / `cc_binary` anymore to compile cgo code. This PR has a ~15% performance penalty in loading and analysis, but if we could create compile / link actions directly, that would go away.

**Comment by steeve** [comment]
I meant being able to generate `cc_library` directly from a rule (returning a `cc` provider) without having to link macros together.

**Comment by steeve** [comment]
Since this commit: https://github.com/bazelbuild/bazel/commit/95a40bea2d0488ba3afc803b9082b16cadef1deb

**Comment by amckague** [comment]
Running this commit rebased on master didn't appear to solve the `undefined: raceenabled` problems I'm seeing in my own build. I'd appreciate pointers on where I can add debugging information to see what's going on. 

In my case we're invoking the protoc rules, have a copy of sys in vendor, and using -race during bazel test. (in case that context helps at all) 
(# gazelle:proto disable-global, or forcing protoc to be statically linked might be part of the picture)
