### ISSUE TITLE
bazel 0.5.3 incompatible with older snapshots of `rules_go` 

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_go#661]
(oops, hit enter too early)

Kubernetes is currently using `rules_go`@ 03c634753160632c00f506afeafc819fbea4c422, which recently started failing to build with bazel 0.5.3:
```
ERROR: [$HOME].cache/bazel/_bazel_/75e5737b0f848bf1b7c3ab3303c8bf72/external/io_bazel_rules_go/go/tools/BUILD:6:1: in go_tool_binary rule @io_bazel_rules_go//go/tools:generate_test_main: 
Traceback (most recent call last):
        File "[$HOME].cache/bazel/_bazel_[$USER]/75e5737b0f848bf1b7c3ab3303c8bf72/external/io_bazel_rules_go/go/tools/BUILD", line 6
                go_tool_binary(name = 'generate_test_main')
        File "[$HOME].cache/bazel/_bazel_[$USER]/75e5737b0f848bf1b7c3ab3303c8bf72/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 35, in _go_tool_binary_impl
                ctx.action(inputs = ((ctx.files.srcs + tool...), <4 more arguments>)
        File "[$HOME].cache/bazel/_bazel_[$USER]/75e5737b0f848bf1b7c3ab3303c8bf72/external/io_bazel_rules_go/go/private/go_tool_binary.bzl", line 36, in ctx.action                                                 
                toolchain.tools
object of type 'Target' has no field 'tools'
```

There's probably nothing actionable here other than an FYI. We'll probably bump our `rules_go` dependencies to get around the issue.

**Comment by jayconrod** [comment]
Yeah, unfortunately there was a breaking change made on the Bazel side a couple weeks ago (bazelbuild/bazel#3387). They fixed rules_go in #620. That should be in 0.5.2. I don't think we're planning to backport that to older versions, unless there's an urgent need.

I'll close this issue since there's nothing to do, but please reopen if you aren't able to upgrade to rules_go 0.5.2, and we can figure out a solution.
