### ISSUE TITLE
C link modes now generate empty header files

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_go#2128]
### What version of rules_go are you using?

master (6b3f7611dd21da0f7b35164ae2acb592009832f2)

### What version of gazelle are you using?

None

### What version of Bazel are you using?

0.27.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS, Ubuntu, amd64

### Any other potentially useful information about your toolchain?

None

### What did you do?

In the tests for C link modes, I converted implicit declaration warnings to errors, and ran the tests.
```
$ git diff
diff --git a/tests/core/c_linkmodes/BUILD.bazel b/tests/core/c_linkmodes/BUILD.bazel
index bd9fbec1..146ad2f9 100644
--- a/tests/core/c_linkmodes/BUILD.bazel
+++ b/tests/core/c_linkmodes/BUILD.bazel
@@ -14,6 +14,7 @@ cc_test(
         "@io_bazel_rules_go//go/platform:windows": ["skip.c"],
         "//conditions:default": ["add_test_archive.c"],
     }),
+    copts = ["-Werror=implicit-function-declaration"],
     deps = select({
         "@io_bazel_rules_go//go/platform:windows": [],
         "//conditions:default": [":adder_archive.cc"],
@@ -34,6 +35,7 @@ cc_test(
         "@io_bazel_rules_go//go/platform:windows": ["skip.c"],
         "//conditions:default": ["add_test_shared.c"],
     }),
+    copts = ["-Werror=implicit-function-declaration"],
     deps = select({
         "@io_bazel_rules_go//go/platform:windows": [],
         "//conditions:default": [":adder_shared.cc"],
```

### What did you expect to see?

The tests should complete successfully without a compile error.

### What did you see instead?

The header file generated by //tests/core/c_linkmodes:adder_shared.c_hdrs is empty. This is verified by visually inspecting the generated file, and by the following compile error:

```
$ bazel test tests/core/c_linkmodes:c-shared_test
...
tests/core/c_linkmodes/add_test_shared.c:5:12: error: implicit declaration of function 'GoAdd' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    assert(GoAdd(42, 42) == 84);
           ^
1 error generated.
...
```

I played a `git bisect`, and found the culprit to be 528f6faf83f85c23da367d61f784893d1b3bd72b. The commit immediately before this builds just fine, and so does rules_go 0.18.7 (latest release).

**Comment by siddharthab** [comment]
Is this condition intentional: https://github.com/bazelbuild/rules_go/blob/6b3f7611dd21da0f7b35164ae2acb592009832f2/go/private/rules/wrappers.bzl#L78-L79

The setup for cgo rules is necessary to collect cgo info. Without cgo info, the output group cgo_exports is not populated, and so the header files are not collected. There could be other side effects.

**Comment by jayconrod** [comment]
This is a regression with the new `GoCompilePkg` action. It's not exposing the export headers.

We should combine export headers in the link action instead of a `genrule` that invokes `cat`. The `genrule` isn't getting any files, so it produces an empty file without error.

And we should have a test that catches this problem =P

**Comment by jayconrod** [comment]
Hmm, I'm not actually sure why we were concatenating these originally. The Go command does not.

**Comment by siddharthab** [comment]
Thank you!

The concatenation is also a problem when headers from unrelated packages are picked up in the filegroup and included in the single header file.

**Comment by jayconrod** [comment]
I opted not to fix the concatenation yet. I'm trying to get a release out this week, so I'm fixing regressions, but the concatenation was the old behavior. Filed #2131 to fix that eventually.

**Comment by siddharthab** [comment]
OK.

I am testing both rules_go and gazelle for regressions on our monorepo. Will file more bugs today, if I come across any.

**Comment by jayconrod** [comment]
Thanks for testing and reporting issues. This has been helpful.

I can't promise all fixes will get into the 0.19.0 release, but they should be in a point release soon after at least. There are a lot of problems with cross-compilation on rules_go 0.18.x with newer versions of Bazel; the fixes for those issues can't be backported, so it's important that 0.19.0 is out sooner rather than later.

**Comment by siddharthab** [comment]
That's fine. Thanks for all your help.

I think there is just one last bug left to file, but that is a bit hard to repro minimally (segfault in assembly code in golang.org/x/crypto when using the c-archives compiled with the new way). Can certainly wait after your release is done. Everything else looks good.

Thanks again.
