### ISSUE TITLE
0.5.0 can't build the latest version of go-sqlite3

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_go#537]
When I build my project after upgrading to 0.5.0, I get the following error.

```
INFO: Found 1 target...
ERROR: /home/achew22/.cache/bazel/_bazel_achew22/b4046dd61443a6da2a0d424d121b9b4a/external/com_github_mattn_go_sqlite3/BUILD.bazel:5:1: error executing shell command: 'bazel-out/local-fastbuild/bin/external/com_github_mattn_go_sqlite3/bazel-out/local-fastbuild/genfiles/external/com_github_mattn_go_sqlite3/cgo_default_library.cgo_codegen.dir/CGoCodeGenFile.params' failed: Process exited with status 1 [sandboxed].
/home/achew22/.cache/bazel/_bazel_achew22/b4046dd61443a6da2a0d424d121b9b4a/bazel-sandbox/1315118602679964528/execroot/$PROJECT/bazel-out/local-fastbuild/genfiles/external/com_github_mattn_go_sqlite3/cgo_default_library.cgo_codegen.dir/external/com_github_mattn_go_sqlite3/backup.go:10:29: fatal error: sqlite3-binding.h: No such file or directory
compilation terminated.
Use --strategy=CGoCodeGen=standalone to disable sandboxing for the failing actions.
Target $TARGET failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.630s, Critical Path: 0.16s
```
I didn't see anything in the release notes that made me think this was expected or that I needed to migrate anything. How can I help collect information for debugging?

**Comment by jayconrod** [comment]
Thanks for reporting. Unfortunately, this is a known issue, #526.

How were you building go-sqlite3 before 0.5.0? Did you use a custom BUILD file or platform-specific tags for Gazelle? I didn't consider this bug a release blocker because were weren't previously able to build go-sqlite3 before with default settings.

**Comment by zombiezen** [comment]
If you bring in sqlite3 separately, you can get go-sqlite3 to work by `-DUSE_LIBSQLITE3` and a custom BUILD for go-sqlite3.
