### ISSUE TITLE
Go version build constraints are all satisfied regardless of the actual go version.

### ISSUE THREAD

**Issue by robotoer** [bazelbuild/rules_go#433]
It seems that filter_tags passes all go versions build constraints regardless of the actual go version being used.

**To reproduce:**

Create a go_library/go_binary target that includes the two files:

_works.go_
```
// +build go1.8


package main

type MyInterface interface {}
type MyImpl struct {}
func MyOtherMethod(other MyInterface) {}

func MyMethod() {
	impl := MyImpl{}

	MyOtherMethod(&impl)
}
```

_errors.go_
```
// +build go1.7


package main

type MyInterface2 interface {
	MethodA()
}
type MyImpl2 struct {}
func MyOtherMethod2(other MyInterface2) {}

func MyMethod2() {
	impl := MyImpl2{}

	MyOtherMethod2(&impl)
}
```

Using a `go_repositories()` should setup the build using go1.8.1 which should only include the first file. What actually happens is both files are included and a build error occurs:
```
error executing shell command: 'bazel-out/local-fastbuild/bin/services/example/golang/cmd/cmd.a.GoCompileFile.params' failed: Process exited with status 1 [sandboxed].
services/example/golang/cmd/contains_errors.go:16: cannot use &impl (type *MyImpl2) as type MyInterface2 in argument to MyOtherMethod2:
	*MyImpl2 does not implement MyInterface2 (missing MethodA method)
Use --strategy=GoCompile=standalone to disable sandboxing for the failing actions.
Target //services/example/golang/cmd:cmd failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.091s, Critical Path: 0.93s
```

Build constraints are partially working since changing the build constraint in _errors.go_ to be:
```
// +build ignore
```
or
```
// +build nonexistenttag
```
the file is not included in the build.

I'm not sure why filter_tags doesn't work quite yet, but it seems that all go versions are satisfied by filter_tags somewhere deep in the go build code.

**Comment by robotoer** [comment]
Ahh, here's the problem: https://github.com/golang/go/blob/master/src/go/build/build.go#L295

**Comment by robotoer** [comment]
Ahh, false alarm. I misunderstood how go build constraints for go versions work: https://golang.org/pkg/go/build/
