### ISSUE TITLE
Not able to compile go-sqlite3 after upgrading to Bazel 3.7

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/rules_go#2688]
### What version of rules_go are you using?

0.24.4

### What version of gazelle are you using?

0.22.0

### What version of Bazel are you using?

3.7

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Darwin and Linux amd64

### Any other potentially useful information about your toolchain?

The same build works in Bazel 3.6 and before.

### What did you do?

```bash
$ git clone git@github.com:linzhp/bazel_examples.git
$ cd bazel_examples
$ bazel build @com_github_mattn_go_sqlite3//:go-sqlite3
```

### What did you expect to see?

Build completed successfully

### What did you see instead?

```
ERROR: /private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/external/com_github_mattn_go_sqlite3/BUILD.bazel:3:11: GoCompilePkg external/com_github_mattn_go_sqlite3/go-sqlite3.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_mattn_go_sqlite3/backup.go -src ... (remaining 65 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_mattn_go_sqlite3/backup.go -src ... (remaining 65 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/sandbox/darwin-sandbox/27/execroot/__main__/external/com_github_mattn_go_sqlite3/backup.go:10:10: error: 'sqlite3-binding.h' file not found with <angled> include; use "quotes" instead
#include <sqlite3-binding.h>
         ^~~~~~~~~~~~~~~~~~~
         "sqlite3-binding.h"
1 error generated.
compilepkg: error running the following subcommand: exit status 2
PATH=external/local_config_cc:/bin:/usr/bin \
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
CGO_ENABLED=1 \
XCODE_VERSION_OVERRIDE=11.5.0.11E608c \
GOARCH=amd64 \
CC=external/local_config_cc/wrapped_clang \
DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
GOPATH= \
GOOS=darwin \
GOROOT=external/go_sdk \
APPLE_SDK_VERSION_OVERRIDE=10.15 \
TMPDIR=/var/folders/bf/3ympgpy92txgknkb4z30dldh0000gn/T/ \
APPLE_SDK_PLATFORM=MacOSX \
GOROOT_FINAL=GOROOT \
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0 \
CGO_LDFLAGS="-fobjc-link-runtime -headerpad_max_install_names -no-canonical-prefixes -mmacosx-version-min=10.15" \
external/go_sdk/pkg/tool/darwin_amd64/cgo -srcdir /private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/sandbox/darwin-sandbox/27/execroot/__main__/external/com_github_mattn_go_sqlite3 -objdir /var/folders/bf/3ympgpy92txgknkb4z30dldh0000gn/T/rules_go_work-059422867 -importpath github.com/mattn/go-sqlite3 -- -I com_github_mattn_go_sqlite3 -iquote external/com_github_mattn_go_sqlite3 -iquote . -iquote /private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/sandbox/darwin-sandbox/27/execroot/__main__/external/com_github_mattn_go_sqlite3 -iquote /var/folders/bf/3ympgpy92txgknkb4z30dldh0000gn/T/rules_go_work-059422867 -D_FORTIFY_SOURCE=1 -fstack-protector -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=10.15 -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=redacted -D__TIMESTAMP__=redacted -D__TIME__=redacted -DHAVE_USLEEP=1 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_DISABLE_INTRINSIC -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_OMIT_DEPRECATED -DSQLITE_THREADSAFE=1 -DSQLITE_TRACE_SIZE_LIMIT=15 -Wno-deprecated-declarations -std=gnu99 -I. -fPIC backup.go callback.go error.go sqlite3.go sqlite3_context.go sqlite3_load_extension.go sqlite3_opt_userauth_omit.go sqlite3_other.go sqlite3_type.go
Target @com_github_mattn_go_sqlite3//:go-sqlite3 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.538s, Critical Path: 0.15s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by jayconrod** [comment]
Duplicate of #2685.

Does this work for you at tip? If someone can confirm, I'll tag a release today.

**Comment by linzhp** [comment]
Sorry for missing #2685. I can confirm it's fixed on tip.
